# This file handles Alembic migration script template
# it defines the template for generating migration files

"""initial schema

Revision ID: 5eb6f7dbd8a2
Revises: 
Create Date: 2025-06-30 18:34:45.975085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eb6f7dbd8a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_brand_id'), 'brand', ['id'], unique=False)
    op.create_table('geo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'brand_id', name='uq_geo_brand')
    )
    op.create_index(op.f('ix_geo_id'), 'geo', ['id'], unique=False)
    op.create_table('manager',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_id')
    )
    op.create_index(op.f('ix_manager_id'), 'manager', ['id'], unique=False)
    op.create_table('fact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geo_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(), nullable=False),
    sa.Column('amount_fact', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['geo_id'], ['geo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('geo_id', 'month', name='uq_fact_geo_month')
    )
    op.create_index(op.f('ix_fact_id'), 'fact', ['id'], unique=False)
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geo_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount_planned', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['geo_id'], ['geo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('geo_id', 'date', name='uq_report_geo_date')
    )
    op.create_index(op.f('ix_report_id'), 'report', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_id'), table_name='report')
    op.drop_table('report')
    op.drop_index(op.f('ix_fact_id'), table_name='fact')
    op.drop_table('fact')
    op.drop_index(op.f('ix_manager_id'), table_name='manager')
    op.drop_table('manager')
    op.drop_index(op.f('ix_geo_id'), table_name='geo')
    op.drop_table('geo')
    op.drop_index(op.f('ix_brand_id'), table_name='brand')
    op.drop_table('brand')
    # ### end Alembic commands ### 